/**
 * Design Warehouse — Seed Corpus
 * ------------------------------------------------------------------
 * Categorized registry of hot-linkable design assets surfaced in the
 * Memelli OS Design Warehouse thumbnail-grid UI.
 *
 * Every `thumbUrl` here was verified to return image bytes (no auth,
 * no referer, no cookies) at ingest time (2026-05-01) using WebFetch.
 *
 * License notes are propagated from each upstream source. When the
 * Warehouse UI surfaces an asset for download/use, the operator must
 * still respect the upstream license terms.
 *
 * NOTE: do not edit this file by hand to add unverified URLs — broken
 * thumbnails wreck the grid. Add via the warehouse intake flow which
 * verifies before persisting, OR re-run the seed builder.
 */

export type WarehouseCategory =
  | "landing-page"
  | "admin-dashboard"
  | "component-library"
  | "icon-set"
  | "illustration"
  | "photo"
  | "pattern-background"
  | "mockup"
  | "font-specimen"
  | "public-domain-art"
  | "ui-kit"
  | "video";

export type WarehouseAsset = {
  id: string;
  name: string;
  category: WarehouseCategory;
  source: string;
  sourceUrl: string;
  thumbUrl: string;
  license: string;
  tags: string[];
  ingestedAt: string;
  signupRequired: false;
};

const ISO = "2026-05-01";

export const WAREHOUSE_SEED: WarehouseAsset[] = [
  // =========================================================================
  // landing-page (Cruip + variations)
  // =========================================================================
  {
    id: "cruip-open-react-hero",
    name: "Open React Template — Hero",
    category: "landing-page",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/open-react-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/open-react-template/master/public/images/hero-image-01.jpg",
    license: "GPL-3.0",
    tags: ["react", "tailwind", "saas", "hero"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-open-react-features",
    name: "Open React Template — Features",
    category: "landing-page",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/open-react-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/open-react-template/master/public/images/features.png",
    license: "GPL-3.0",
    tags: ["react", "tailwind", "saas", "features"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-open-react-workflow-01",
    name: "Open React Template — Workflow 01",
    category: "landing-page",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/open-react-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/open-react-template/master/public/images/workflow-01.png",
    license: "GPL-3.0",
    tags: ["react", "tailwind", "saas", "workflow"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-open-react-workflow-02",
    name: "Open React Template — Workflow 02",
    category: "landing-page",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/open-react-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/open-react-template/master/public/images/workflow-02.png",
    license: "GPL-3.0",
    tags: ["react", "tailwind", "saas", "workflow"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-open-react-workflow-03",
    name: "Open React Template — Workflow 03",
    category: "landing-page",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/open-react-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/open-react-template/master/public/images/workflow-03.png",
    license: "GPL-3.0",
    tags: ["react", "tailwind", "saas", "workflow"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-tailwind-landing-planet",
    name: "Tailwind Landing — Planet Hero",
    category: "landing-page",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/tailwind-landing-page-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/tailwind-landing-page-template/main/public/images/planet.png",
    license: "GPL-3.0",
    tags: ["tailwind", "saas", "hero", "planet"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-tailwind-landing-large-testimonial",
    name: "Tailwind Landing — Large Testimonial",
    category: "landing-page",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/tailwind-landing-page-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/tailwind-landing-page-template/main/public/images/large-testimonial.jpg",
    license: "GPL-3.0",
    tags: ["tailwind", "saas", "testimonial"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-tailwind-landing-auth-bg",
    name: "Tailwind Landing — Auth Background",
    category: "landing-page",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/tailwind-landing-page-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/tailwind-landing-page-template/main/public/images/auth-bg.svg",
    license: "GPL-3.0",
    tags: ["tailwind", "auth", "background"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-tailwind-landing-stripes",
    name: "Tailwind Landing — Stripes Decor",
    category: "landing-page",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/tailwind-landing-page-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/tailwind-landing-page-template/main/public/images/stripes.svg",
    license: "GPL-3.0",
    tags: ["tailwind", "decor"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-open-react-page-illustration",
    name: "Open React — Page Illustration",
    category: "landing-page",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/open-react-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/open-react-template/master/public/images/page-illustration.svg",
    license: "GPL-3.0",
    tags: ["react", "tailwind", "decor"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-cards-waterfall-illustration-01",
    name: "Cruip Tutorial — Cards Waterfall 01",
    category: "landing-page",
    source: "Cruip Tutorials / GitHub",
    sourceUrl: "https://github.com/cruip/cruip-tutorials",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/cruip-tutorials/main/cards-waterfall/illustration-01.png",
    license: "GPL-3.0",
    tags: ["cards", "illustration", "tutorial"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-cards-waterfall-illustration-02",
    name: "Cruip Tutorial — Cards Waterfall 02",
    category: "landing-page",
    source: "Cruip Tutorials / GitHub",
    sourceUrl: "https://github.com/cruip/cruip-tutorials",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/cruip-tutorials/main/cards-waterfall/illustration-02.png",
    license: "GPL-3.0",
    tags: ["cards", "illustration", "tutorial"],
    ingestedAt: ISO,
    signupRequired: false,
  },

  // =========================================================================
  // admin-dashboard (Cruip dashboard repos)
  // =========================================================================
  {
    id: "cruip-tailwind-dashboard-icon-01",
    name: "Tailwind Dashboard — Icon Card 01",
    category: "admin-dashboard",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/tailwind-dashboard-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/tailwind-dashboard-template/main/src/images/icon-01.svg",
    license: "GPL-3.0",
    tags: ["dashboard", "tailwind", "react", "icon"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-tailwind-dashboard-icon-02",
    name: "Tailwind Dashboard — Icon Card 02",
    category: "admin-dashboard",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/tailwind-dashboard-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/tailwind-dashboard-template/main/src/images/icon-02.svg",
    license: "GPL-3.0",
    tags: ["dashboard", "tailwind", "icon"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-tailwind-dashboard-icon-03",
    name: "Tailwind Dashboard — Icon Card 03",
    category: "admin-dashboard",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/tailwind-dashboard-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/tailwind-dashboard-template/main/src/images/icon-03.svg",
    license: "GPL-3.0",
    tags: ["dashboard", "tailwind", "icon"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-tailwind-dashboard-user-32",
    name: "Tailwind Dashboard — User Avatar",
    category: "admin-dashboard",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/tailwind-dashboard-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/tailwind-dashboard-template/main/src/images/user-avatar-32.png",
    license: "GPL-3.0",
    tags: ["dashboard", "tailwind", "avatar"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-laravel-dashboard-auth",
    name: "Laravel Tailwind Dashboard — Auth Image",
    category: "admin-dashboard",
    source: "Cruip / GitHub",
    sourceUrl:
      "https://github.com/cruip/laravel-tailwindcss-admin-dashboard-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/laravel-tailwindcss-admin-dashboard-template/main/public/images/auth-image.jpg",
    license: "GPL-3.0",
    tags: ["dashboard", "laravel", "tailwind", "auth"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-laravel-dashboard-404",
    name: "Laravel Dashboard — 404 Illustration",
    category: "admin-dashboard",
    source: "Cruip / GitHub",
    sourceUrl:
      "https://github.com/cruip/laravel-tailwindcss-admin-dashboard-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/laravel-tailwindcss-admin-dashboard-template/main/public/images/404-illustration.svg",
    license: "GPL-3.0",
    tags: ["dashboard", "laravel", "404"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-vuejs-dashboard-icon-01",
    name: "Vue.js Dashboard — Icon Card",
    category: "admin-dashboard",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/vuejs-admin-dashboard-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/vuejs-admin-dashboard-template/main/src/images/icon-01.svg",
    license: "GPL-3.0",
    tags: ["dashboard", "vue", "icon"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-vuejs-dashboard-user-avatar",
    name: "Vue.js Dashboard — User Avatar",
    category: "admin-dashboard",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/vuejs-admin-dashboard-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/vuejs-admin-dashboard-template/main/src/images/user-avatar-32.png",
    license: "GPL-3.0",
    tags: ["dashboard", "vue", "avatar"],
    ingestedAt: ISO,
    signupRequired: false,
  },

  // =========================================================================
  // component-library (Heroicons / Tabler / Lucide / Bootstrap Icons)
  // =========================================================================
  {
    id: "heroicons-academic-cap",
    name: "Heroicons — Academic Cap",
    category: "component-library",
    source: "Tailwind Labs / GitHub",
    sourceUrl: "https://github.com/tailwindlabs/heroicons",
    thumbUrl:
      "https://raw.githubusercontent.com/tailwindlabs/heroicons/master/optimized/24/outline/academic-cap.svg",
    license: "MIT",
    tags: ["heroicons", "outline", "education"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "heroicons-bell",
    name: "Heroicons — Bell",
    category: "component-library",
    source: "Tailwind Labs / GitHub",
    sourceUrl: "https://github.com/tailwindlabs/heroicons",
    thumbUrl:
      "https://raw.githubusercontent.com/tailwindlabs/heroicons/master/optimized/24/outline/bell.svg",
    license: "MIT",
    tags: ["heroicons", "outline", "notification"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "heroicons-bookmark",
    name: "Heroicons — Bookmark",
    category: "component-library",
    source: "Tailwind Labs / GitHub",
    sourceUrl: "https://github.com/tailwindlabs/heroicons",
    thumbUrl:
      "https://raw.githubusercontent.com/tailwindlabs/heroicons/master/optimized/24/outline/bookmark.svg",
    license: "MIT",
    tags: ["heroicons", "outline", "save"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "heroicons-archive-box",
    name: "Heroicons — Archive Box",
    category: "component-library",
    source: "Tailwind Labs / GitHub",
    sourceUrl: "https://github.com/tailwindlabs/heroicons",
    thumbUrl:
      "https://raw.githubusercontent.com/tailwindlabs/heroicons/master/optimized/24/outline/archive-box.svg",
    license: "MIT",
    tags: ["heroicons", "outline", "archive"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "heroicons-heart-outline",
    name: "Heroicons — Heart",
    category: "component-library",
    source: "Tailwind Labs / GitHub",
    sourceUrl: "https://github.com/tailwindlabs/heroicons",
    thumbUrl:
      "https://raw.githubusercontent.com/tailwindlabs/heroicons/master/optimized/24/outline/heart.svg",
    license: "MIT",
    tags: ["heroicons", "outline", "love"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "tabler-home",
    name: "Tabler — Home",
    category: "component-library",
    source: "Tabler / GitHub",
    sourceUrl: "https://github.com/tabler/tabler-icons",
    thumbUrl:
      "https://raw.githubusercontent.com/tabler/tabler-icons/main/icons/outline/home.svg",
    license: "MIT",
    tags: ["tabler", "outline", "navigation"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "tabler-address-book",
    name: "Tabler — Address Book",
    category: "component-library",
    source: "Tabler / GitHub",
    sourceUrl: "https://github.com/tabler/tabler-icons",
    thumbUrl:
      "https://raw.githubusercontent.com/tabler/tabler-icons/main/icons/outline/address-book.svg",
    license: "MIT",
    tags: ["tabler", "outline", "contacts"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "tabler-accessible",
    name: "Tabler — Accessible",
    category: "component-library",
    source: "Tabler / GitHub",
    sourceUrl: "https://github.com/tabler/tabler-icons",
    thumbUrl:
      "https://raw.githubusercontent.com/tabler/tabler-icons/main/icons/outline/accessible.svg",
    license: "MIT",
    tags: ["tabler", "outline", "a11y"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "bootstrap-icons-heart",
    name: "Bootstrap Icons — Heart",
    category: "component-library",
    source: "Bootstrap / GitHub",
    sourceUrl: "https://github.com/twbs/icons",
    thumbUrl:
      "https://raw.githubusercontent.com/twbs/icons/main/icons/heart.svg",
    license: "MIT",
    tags: ["bootstrap", "heart"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "bootstrap-icons-alarm",
    name: "Bootstrap Icons — Alarm",
    category: "component-library",
    source: "Bootstrap / GitHub",
    sourceUrl: "https://github.com/twbs/icons",
    thumbUrl:
      "https://raw.githubusercontent.com/twbs/icons/main/icons/alarm.svg",
    license: "MIT",
    tags: ["bootstrap", "alarm"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "bootstrap-icons-archive",
    name: "Bootstrap Icons — Archive",
    category: "component-library",
    source: "Bootstrap / GitHub",
    sourceUrl: "https://github.com/twbs/icons",
    thumbUrl:
      "https://raw.githubusercontent.com/twbs/icons/main/icons/archive.svg",
    license: "MIT",
    tags: ["bootstrap", "archive"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "lucide-heart",
    name: "Lucide — Heart",
    category: "component-library",
    source: "Lucide / GitHub",
    sourceUrl: "https://github.com/lucide-icons/lucide",
    thumbUrl:
      "https://raw.githubusercontent.com/lucide-icons/lucide/main/icons/heart.svg",
    license: "ISC",
    tags: ["lucide", "heart"],
    ingestedAt: ISO,
    signupRequired: false,
  },

  // =========================================================================
  // icon-set (SuperTinyIcons brand SVGs + Lucide variety)
  // =========================================================================
  {
    id: "supertiny-github",
    name: "SuperTiny — GitHub",
    category: "icon-set",
    source: "edent / SuperTinyIcons",
    sourceUrl: "https://github.com/edent/SuperTinyIcons",
    thumbUrl:
      "https://raw.githubusercontent.com/edent/SuperTinyIcons/master/images/svg/github.svg",
    license: "MIT",
    tags: ["brand", "github", "logo"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "supertiny-google",
    name: "SuperTiny — Google",
    category: "icon-set",
    source: "edent / SuperTinyIcons",
    sourceUrl: "https://github.com/edent/SuperTinyIcons",
    thumbUrl:
      "https://raw.githubusercontent.com/edent/SuperTinyIcons/master/images/svg/google.svg",
    license: "MIT",
    tags: ["brand", "google", "logo"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "supertiny-apple",
    name: "SuperTiny — Apple",
    category: "icon-set",
    source: "edent / SuperTinyIcons",
    sourceUrl: "https://github.com/edent/SuperTinyIcons",
    thumbUrl:
      "https://raw.githubusercontent.com/edent/SuperTinyIcons/master/images/svg/apple.svg",
    license: "MIT",
    tags: ["brand", "apple", "logo"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "supertiny-microsoft",
    name: "SuperTiny — Microsoft",
    category: "icon-set",
    source: "edent / SuperTinyIcons",
    sourceUrl: "https://github.com/edent/SuperTinyIcons",
    thumbUrl:
      "https://raw.githubusercontent.com/edent/SuperTinyIcons/master/images/svg/microsoft.svg",
    license: "MIT",
    tags: ["brand", "microsoft", "logo"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "supertiny-amazon",
    name: "SuperTiny — Amazon",
    category: "icon-set",
    source: "edent / SuperTinyIcons",
    sourceUrl: "https://github.com/edent/SuperTinyIcons",
    thumbUrl:
      "https://raw.githubusercontent.com/edent/SuperTinyIcons/master/images/svg/amazon.svg",
    license: "MIT",
    tags: ["brand", "amazon", "logo"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "supertiny-facebook",
    name: "SuperTiny — Facebook",
    category: "icon-set",
    source: "edent / SuperTinyIcons",
    sourceUrl: "https://github.com/edent/SuperTinyIcons",
    thumbUrl:
      "https://raw.githubusercontent.com/edent/SuperTinyIcons/master/images/svg/facebook.svg",
    license: "MIT",
    tags: ["brand", "facebook", "logo", "social"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "supertiny-twitter",
    name: "SuperTiny — Twitter",
    category: "icon-set",
    source: "edent / SuperTinyIcons",
    sourceUrl: "https://github.com/edent/SuperTinyIcons",
    thumbUrl:
      "https://raw.githubusercontent.com/edent/SuperTinyIcons/master/images/svg/twitter.svg",
    license: "MIT",
    tags: ["brand", "twitter", "logo", "social"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "supertiny-spotify",
    name: "SuperTiny — Spotify",
    category: "icon-set",
    source: "edent / SuperTinyIcons",
    sourceUrl: "https://github.com/edent/SuperTinyIcons",
    thumbUrl:
      "https://raw.githubusercontent.com/edent/SuperTinyIcons/master/images/svg/spotify.svg",
    license: "MIT",
    tags: ["brand", "spotify", "logo", "music"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "supertiny-docker",
    name: "SuperTiny — Docker",
    category: "icon-set",
    source: "edent / SuperTinyIcons",
    sourceUrl: "https://github.com/edent/SuperTinyIcons",
    thumbUrl:
      "https://raw.githubusercontent.com/edent/SuperTinyIcons/master/images/svg/docker.svg",
    license: "MIT",
    tags: ["brand", "docker", "logo", "dev"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "supertiny-1password",
    name: "SuperTiny — 1Password",
    category: "icon-set",
    source: "edent / SuperTinyIcons",
    sourceUrl: "https://github.com/edent/SuperTinyIcons",
    thumbUrl:
      "https://raw.githubusercontent.com/edent/SuperTinyIcons/master/images/svg/1password.svg",
    license: "MIT",
    tags: ["brand", "1password", "logo", "security"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "lucide-star",
    name: "Lucide — Star",
    category: "icon-set",
    source: "Lucide / GitHub",
    sourceUrl: "https://github.com/lucide-icons/lucide",
    thumbUrl:
      "https://raw.githubusercontent.com/lucide-icons/lucide/main/icons/star.svg",
    license: "ISC",
    tags: ["lucide", "star"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "lucide-airplay",
    name: "Lucide — Airplay",
    category: "icon-set",
    source: "Lucide / GitHub",
    sourceUrl: "https://github.com/lucide-icons/lucide",
    thumbUrl:
      "https://raw.githubusercontent.com/lucide-icons/lucide/main/icons/airplay.svg",
    license: "ISC",
    tags: ["lucide", "airplay"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "lucide-anchor",
    name: "Lucide — Anchor",
    category: "icon-set",
    source: "Lucide / GitHub",
    sourceUrl: "https://github.com/lucide-icons/lucide",
    thumbUrl:
      "https://raw.githubusercontent.com/lucide-icons/lucide/main/icons/anchor.svg",
    license: "ISC",
    tags: ["lucide", "anchor"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "lucide-album",
    name: "Lucide — Album",
    category: "icon-set",
    source: "Lucide / GitHub",
    sourceUrl: "https://github.com/lucide-icons/lucide",
    thumbUrl:
      "https://raw.githubusercontent.com/lucide-icons/lucide/main/icons/album.svg",
    license: "ISC",
    tags: ["lucide", "album"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "lucide-activity",
    name: "Lucide — Activity",
    category: "icon-set",
    source: "Lucide / GitHub",
    sourceUrl: "https://github.com/lucide-icons/lucide",
    thumbUrl:
      "https://raw.githubusercontent.com/lucide-icons/lucide/main/icons/activity.svg",
    license: "ISC",
    tags: ["lucide", "activity"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "lucide-accessibility",
    name: "Lucide — Accessibility",
    category: "icon-set",
    source: "Lucide / GitHub",
    sourceUrl: "https://github.com/lucide-icons/lucide",
    thumbUrl:
      "https://raw.githubusercontent.com/lucide-icons/lucide/main/icons/accessibility.svg",
    license: "ISC",
    tags: ["lucide", "a11y"],
    ingestedAt: ISO,
    signupRequired: false,
  },

  // =========================================================================
  // illustration (Cruip illustrations + svg blurred shapes / footers)
  // =========================================================================
  {
    id: "cruip-open-react-blurred-shape",
    name: "Open React — Blurred Shape",
    category: "illustration",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/open-react-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/open-react-template/master/public/images/blurred-shape.svg",
    license: "GPL-3.0",
    tags: ["abstract", "blob", "decor"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-open-react-blurred-shape-gray",
    name: "Open React — Blurred Shape Gray",
    category: "illustration",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/open-react-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/open-react-template/master/public/images/blurred-shape-gray.svg",
    license: "GPL-3.0",
    tags: ["abstract", "blob", "decor"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-open-react-footer-illustration",
    name: "Open React — Footer Illustration",
    category: "illustration",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/open-react-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/open-react-template/master/public/images/footer-illustration.svg",
    license: "GPL-3.0",
    tags: ["footer", "decor"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-open-react-secondary-illustration",
    name: "Open React — Secondary Illustration",
    category: "illustration",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/open-react-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/open-react-template/master/public/images/secondary-illustration.svg",
    license: "GPL-3.0",
    tags: ["abstract", "decor"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-tailwind-stripes-dark",
    name: "Tailwind Landing — Stripes Dark",
    category: "illustration",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/tailwind-landing-page-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/tailwind-landing-page-template/main/public/images/stripes-dark.svg",
    license: "GPL-3.0",
    tags: ["stripes", "decor"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-tailwind-planet-overlay",
    name: "Tailwind — Planet Overlay",
    category: "illustration",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/tailwind-landing-page-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/tailwind-landing-page-template/main/public/images/planet-overlay.svg",
    license: "GPL-3.0",
    tags: ["space", "planet", "overlay"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-tailwind-planet-tag-01",
    name: "Tailwind — Planet Tag 01",
    category: "illustration",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/tailwind-landing-page-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/tailwind-landing-page-template/main/public/images/planet-tag-01.png",
    license: "GPL-3.0",
    tags: ["space", "planet", "ui-decor"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-tailwind-planet-tag-02",
    name: "Tailwind — Planet Tag 02",
    category: "illustration",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/tailwind-landing-page-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/tailwind-landing-page-template/main/public/images/planet-tag-02.png",
    license: "GPL-3.0",
    tags: ["space", "planet"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-tailwind-planet-tag-03",
    name: "Tailwind — Planet Tag 03",
    category: "illustration",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/tailwind-landing-page-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/tailwind-landing-page-template/main/public/images/planet-tag-03.png",
    license: "GPL-3.0",
    tags: ["space", "planet"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-tailwind-planet-tag-04",
    name: "Tailwind — Planet Tag 04",
    category: "illustration",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/tailwind-landing-page-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/tailwind-landing-page-template/main/public/images/planet-tag-04.png",
    license: "GPL-3.0",
    tags: ["space", "planet"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-cards-hover-01",
    name: "Cards Hover Effect — Card 01",
    category: "illustration",
    source: "Cruip Tutorials / GitHub",
    sourceUrl: "https://github.com/cruip/cruip-tutorials",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/cruip-tutorials/main/cards-hover-effect/card-01.png",
    license: "GPL-3.0",
    tags: ["card", "hover", "tutorial"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-cards-hover-01-hover",
    name: "Cards Hover Effect — Card 01 Hover",
    category: "illustration",
    source: "Cruip Tutorials / GitHub",
    sourceUrl: "https://github.com/cruip/cruip-tutorials",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/cruip-tutorials/main/cards-hover-effect/card-01-hover.png",
    license: "GPL-3.0",
    tags: ["card", "hover", "tutorial"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-cards-hover-02",
    name: "Cards Hover Effect — Card 02",
    category: "illustration",
    source: "Cruip Tutorials / GitHub",
    sourceUrl: "https://github.com/cruip/cruip-tutorials",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/cruip-tutorials/main/cards-hover-effect/card-02.png",
    license: "GPL-3.0",
    tags: ["card", "hover", "tutorial"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-cards-hover-02-hover",
    name: "Cards Hover Effect — Card 02 Hover",
    category: "illustration",
    source: "Cruip Tutorials / GitHub",
    sourceUrl: "https://github.com/cruip/cruip-tutorials",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/cruip-tutorials/main/cards-hover-effect/card-02-hover.png",
    license: "GPL-3.0",
    tags: ["card", "hover", "tutorial"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-cards-hover-03",
    name: "Cards Hover Effect — Card 03",
    category: "illustration",
    source: "Cruip Tutorials / GitHub",
    sourceUrl: "https://github.com/cruip/cruip-tutorials",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/cruip-tutorials/main/cards-hover-effect/card-03.png",
    license: "GPL-3.0",
    tags: ["card", "hover", "tutorial"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-cards-hover-03-hover",
    name: "Cards Hover Effect — Card 03 Hover",
    category: "illustration",
    source: "Cruip Tutorials / GitHub",
    sourceUrl: "https://github.com/cruip/cruip-tutorials",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/cruip-tutorials/main/cards-hover-effect/card-03-hover.png",
    license: "GPL-3.0",
    tags: ["card", "hover", "tutorial"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-spotlight-card-01",
    name: "Spotlight Effect — Card 01",
    category: "illustration",
    source: "Cruip Tutorials / GitHub",
    sourceUrl: "https://github.com/cruip/cruip-tutorials",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/cruip-tutorials/main/spotlight-effect/card-01.png",
    license: "GPL-3.0",
    tags: ["card", "spotlight", "tutorial"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-spotlight-card-02",
    name: "Spotlight Effect — Card 02",
    category: "illustration",
    source: "Cruip Tutorials / GitHub",
    sourceUrl: "https://github.com/cruip/cruip-tutorials",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/cruip-tutorials/main/spotlight-effect/card-02.png",
    license: "GPL-3.0",
    tags: ["card", "spotlight", "tutorial"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-spotlight-card-03",
    name: "Spotlight Effect — Card 03",
    category: "illustration",
    source: "Cruip Tutorials / GitHub",
    sourceUrl: "https://github.com/cruip/cruip-tutorials",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/cruip-tutorials/main/spotlight-effect/card-03.png",
    license: "GPL-3.0",
    tags: ["card", "spotlight", "tutorial"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-cards-waterfall-illustration-03",
    name: "Cards Waterfall — Illustration 03",
    category: "illustration",
    source: "Cruip Tutorials / GitHub",
    sourceUrl: "https://github.com/cruip/cruip-tutorials",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/cruip-tutorials/main/cards-waterfall/illustration-03.png",
    license: "GPL-3.0",
    tags: ["cards", "waterfall", "tutorial"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-tailwind-logo-cluster-01",
    name: "Tailwind Landing — Logo 01",
    category: "illustration",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/tailwind-landing-page-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/tailwind-landing-page-template/main/public/images/logo-01.svg",
    license: "GPL-3.0",
    tags: ["logo", "client"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-tailwind-logo-cluster-02",
    name: "Tailwind Landing — Logo 02",
    category: "illustration",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/tailwind-landing-page-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/tailwind-landing-page-template/main/public/images/logo-02.svg",
    license: "GPL-3.0",
    tags: ["logo", "client"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-tailwind-logo-cluster-03",
    name: "Tailwind Landing — Logo 03",
    category: "illustration",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/tailwind-landing-page-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/tailwind-landing-page-template/main/public/images/logo-03.svg",
    license: "GPL-3.0",
    tags: ["logo", "client"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-open-react-client-logo-01",
    name: "Open React — Client Logo 01",
    category: "illustration",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/open-react-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/open-react-template/master/public/images/client-logo-01.svg",
    license: "GPL-3.0",
    tags: ["logo", "client"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-open-react-client-logo-02",
    name: "Open React — Client Logo 02",
    category: "illustration",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/open-react-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/open-react-template/master/public/images/client-logo-02.svg",
    license: "GPL-3.0",
    tags: ["logo", "client"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-open-react-client-logo-03",
    name: "Open React — Client Logo 03",
    category: "illustration",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/open-react-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/open-react-template/master/public/images/client-logo-03.svg",
    license: "GPL-3.0",
    tags: ["logo", "client"],
    ingestedAt: ISO,
    signupRequired: false,
  },

  // =========================================================================
  // photo (Unsplash + Pexels)
  // =========================================================================
  {
    id: "unsplash-mountain-lake",
    name: "Mountain Lake at Dawn",
    category: "photo",
    source: "Unsplash",
    sourceUrl: "https://unsplash.com/photos/Hli3R6LKibo",
    thumbUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
    license: "Unsplash License",
    tags: ["nature", "mountains", "lake", "dawn"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "unsplash-forest-canopy",
    name: "Forest Canopy from Below",
    category: "photo",
    source: "Unsplash",
    sourceUrl: "https://unsplash.com/photos/eCnsoIeZ87w",
    thumbUrl: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800",
    license: "Unsplash License",
    tags: ["nature", "forest", "canopy", "trees"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "unsplash-meadow-trees",
    name: "Meadow with Solo Tree",
    category: "photo",
    source: "Unsplash",
    sourceUrl: "https://unsplash.com/photos/3xigwR3FFYY",
    thumbUrl: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800",
    license: "Unsplash License",
    tags: ["nature", "meadow", "tree", "field"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "unsplash-tropical-beach",
    name: "Tropical Beach Aerial",
    category: "photo",
    source: "Unsplash",
    sourceUrl: "https://unsplash.com/photos/8Myh76_3M2U",
    thumbUrl: "https://images.unsplash.com/photo-1426604966848-d7adac402bff?w=800",
    license: "Unsplash License",
    tags: ["nature", "beach", "ocean", "aerial"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "unsplash-coffee-laptop",
    name: "Coffee on Laptop",
    category: "photo",
    source: "Unsplash",
    sourceUrl: "https://unsplash.com/photos/yo01Z-9HQAw",
    thumbUrl: "https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?w=800",
    license: "Unsplash License",
    tags: ["work", "coffee", "laptop", "desk"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "unsplash-conference-room",
    name: "Conference Room at Sunset",
    category: "photo",
    source: "Unsplash",
    sourceUrl: "https://unsplash.com/photos/mEZ3PoFGs_k",
    thumbUrl: "https://images.unsplash.com/photo-1518837695005-2083093ee35b?w=800",
    license: "Unsplash License",
    tags: ["business", "office", "meeting"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "unsplash-city-night",
    name: "City Skyline at Night",
    category: "photo",
    source: "Unsplash",
    sourceUrl: "https://unsplash.com/photos/T7K4aEPoGGk",
    thumbUrl: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800",
    license: "Unsplash License",
    tags: ["city", "skyline", "night", "urban"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "unsplash-foggy-pines",
    name: "Foggy Pine Forest",
    category: "photo",
    source: "Unsplash",
    sourceUrl: "https://unsplash.com/photos/2Ts5HnA67k8",
    thumbUrl: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=800",
    license: "Unsplash License",
    tags: ["nature", "fog", "forest", "moody"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "unsplash-stars-mountains",
    name: "Stars Over Mountains",
    category: "photo",
    source: "Unsplash",
    sourceUrl: "https://unsplash.com/photos/Lf_PuARIWegxM",
    thumbUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
    license: "Unsplash License",
    tags: ["nature", "night", "stars", "mountains"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "unsplash-developer-workstation",
    name: "Developer Workstation",
    category: "photo",
    source: "Unsplash",
    sourceUrl: "https://unsplash.com/photos/B-x4VaIriRc",
    thumbUrl: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800",
    license: "Unsplash License",
    tags: ["developer", "code", "macbook"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "unsplash-tech-cables",
    name: "Tech Cables Macro",
    category: "photo",
    source: "Unsplash",
    sourceUrl: "https://unsplash.com/photos/9sTlIY-NRMs",
    thumbUrl: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800",
    license: "Unsplash License",
    tags: ["tech", "macro", "hardware"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "unsplash-ide-screen",
    name: "Code on IDE Screen",
    category: "photo",
    source: "Unsplash",
    sourceUrl: "https://unsplash.com/photos/95YRwf6CNw8",
    thumbUrl: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800",
    license: "Unsplash License",
    tags: ["code", "ide", "developer"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "unsplash-team-around-table",
    name: "Team Around Table",
    category: "photo",
    source: "Unsplash",
    sourceUrl: "https://unsplash.com/photos/hDyO6rr3kqk",
    thumbUrl: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800",
    license: "Unsplash License",
    tags: ["team", "collaboration", "office"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "unsplash-laptop-coffee-notes",
    name: "Laptop, Coffee, Notes",
    category: "photo",
    source: "Unsplash",
    sourceUrl: "https://unsplash.com/photos/nGoCgvB5pUw",
    thumbUrl: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800",
    license: "Unsplash License",
    tags: ["work", "laptop", "desk"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "unsplash-circuit-board",
    name: "Circuit Board Macro",
    category: "photo",
    source: "Unsplash",
    sourceUrl: "https://unsplash.com/photos/YK0HPwWDJ1I",
    thumbUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800",
    license: "Unsplash License",
    tags: ["tech", "hardware", "circuit"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "unsplash-iphone-pencil",
    name: "iPhone with Apple Pencil",
    category: "photo",
    source: "Unsplash",
    sourceUrl: "https://unsplash.com/photos/y_Qcl6xV27I",
    thumbUrl: "https://images.unsplash.com/photo-1482938289607-e9573fc25ebb?w=800",
    license: "Unsplash License",
    tags: ["mobile", "design", "apple"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "unsplash-wood-grain-desk",
    name: "Wood Grain Desk",
    category: "photo",
    source: "Unsplash",
    sourceUrl: "https://unsplash.com/photos/SmkalBEhk4g",
    thumbUrl: "https://images.unsplash.com/photo-1494526585095-c41746248156?w=800",
    license: "Unsplash License",
    tags: ["wood", "texture", "desk"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "unsplash-camera-old",
    name: "Vintage Camera Closeup",
    category: "photo",
    source: "Unsplash",
    sourceUrl: "https://unsplash.com/photos/LF8gK8-HGUg",
    thumbUrl: "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800",
    license: "Unsplash License",
    tags: ["camera", "vintage", "photography"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "pexels-business-handshake",
    name: "Business Handshake",
    category: "photo",
    source: "Pexels",
    sourceUrl: "https://www.pexels.com/photo/2422294/",
    thumbUrl:
      "https://images.pexels.com/photos/2422294/pexels-photo-2422294.jpeg?auto=compress&cs=tinysrgb&w=800",
    license: "Pexels License",
    tags: ["business", "people", "handshake"],
    ingestedAt: ISO,
    signupRequired: false,
  },

  // =========================================================================
  // pattern-background (jsDelivr device + cruip + commons)
  // =========================================================================
  {
    id: "cruip-stripes-pattern",
    name: "Stripes Pattern",
    category: "pattern-background",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/tailwind-landing-page-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/tailwind-landing-page-template/main/public/images/stripes.svg",
    license: "GPL-3.0",
    tags: ["stripes", "decor", "pattern"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-stripes-dark-pattern",
    name: "Stripes Dark Pattern",
    category: "pattern-background",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/tailwind-landing-page-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/tailwind-landing-page-template/main/public/images/stripes-dark.svg",
    license: "GPL-3.0",
    tags: ["stripes", "decor", "pattern", "dark"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-noise-pattern",
    name: "Noise Texture",
    category: "pattern-background",
    source: "Cruip Tutorials / GitHub",
    sourceUrl: "https://github.com/cruip/cruip-tutorials",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/cruip-tutorials/main/cards-hover-effect/noise.png",
    license: "GPL-3.0",
    tags: ["noise", "grain", "texture"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-blurred-shape-pattern",
    name: "Blurred Blob Pattern",
    category: "pattern-background",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/open-react-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/open-react-template/master/public/images/blurred-shape.svg",
    license: "GPL-3.0",
    tags: ["blob", "blur", "pattern"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-blurred-shape-gray-pattern",
    name: "Blurred Blob Gray",
    category: "pattern-background",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/open-react-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/open-react-template/master/public/images/blurred-shape-gray.svg",
    license: "GPL-3.0",
    tags: ["blob", "blur", "pattern", "gray"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-page-illustration-bg",
    name: "Page Illustration Background",
    category: "pattern-background",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/open-react-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/open-react-template/master/public/images/page-illustration.svg",
    license: "GPL-3.0",
    tags: ["page", "background"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-auth-bg-pattern",
    name: "Auth Background Pattern",
    category: "pattern-background",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/tailwind-landing-page-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/tailwind-landing-page-template/main/public/images/auth-bg.svg",
    license: "GPL-3.0",
    tags: ["auth", "background"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-footer-illustration-pattern",
    name: "Footer Illustration BG",
    category: "pattern-background",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/open-react-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/open-react-template/master/public/images/footer-illustration.svg",
    license: "GPL-3.0",
    tags: ["footer", "background"],
    ingestedAt: ISO,
    signupRequired: false,
  },

  // =========================================================================
  // mockup (mcapelle iDevices-templates SVGs)
  // =========================================================================
  {
    id: "idevices-iphone5-portrait",
    name: "iPhone 5 — Portrait Mockup",
    category: "mockup",
    source: "mcapelle / iDevices-templates",
    sourceUrl: "https://github.com/mcapelle/iDevices-templates",
    thumbUrl:
      "https://raw.githubusercontent.com/mcapelle/iDevices-templates/master/iphone5-portrait.svg",
    license: "MIT",
    tags: ["iphone", "mockup", "portrait"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "idevices-iphone5-landscape",
    name: "iPhone 5 — Landscape Mockup",
    category: "mockup",
    source: "mcapelle / iDevices-templates",
    sourceUrl: "https://github.com/mcapelle/iDevices-templates",
    thumbUrl:
      "https://raw.githubusercontent.com/mcapelle/iDevices-templates/master/iphone5-landscape.svg",
    license: "MIT",
    tags: ["iphone", "mockup", "landscape"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "idevices-iphone4-portrait",
    name: "iPhone 4 — Portrait Mockup",
    category: "mockup",
    source: "mcapelle / iDevices-templates",
    sourceUrl: "https://github.com/mcapelle/iDevices-templates",
    thumbUrl:
      "https://raw.githubusercontent.com/mcapelle/iDevices-templates/master/iphone4-portrait.svg",
    license: "MIT",
    tags: ["iphone", "mockup", "portrait", "vintage"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "idevices-ipad-portrait",
    name: "iPad — Portrait Mockup",
    category: "mockup",
    source: "mcapelle / iDevices-templates",
    sourceUrl: "https://github.com/mcapelle/iDevices-templates",
    thumbUrl:
      "https://raw.githubusercontent.com/mcapelle/iDevices-templates/master/ipad-portrait.svg",
    license: "MIT",
    tags: ["ipad", "mockup", "portrait"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "idevices-ipad-landscape",
    name: "iPad — Landscape Mockup",
    category: "mockup",
    source: "mcapelle / iDevices-templates",
    sourceUrl: "https://github.com/mcapelle/iDevices-templates",
    thumbUrl:
      "https://raw.githubusercontent.com/mcapelle/iDevices-templates/master/ipad-landscape.svg",
    license: "MIT",
    tags: ["ipad", "mockup", "landscape"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "idevices-iphone4-landscape",
    name: "iPhone 4 — Landscape Mockup",
    category: "mockup",
    source: "mcapelle / iDevices-templates",
    sourceUrl: "https://github.com/mcapelle/iDevices-templates",
    thumbUrl:
      "https://raw.githubusercontent.com/mcapelle/iDevices-templates/master/iphone4-landscape.svg",
    license: "MIT",
    tags: ["iphone", "mockup", "landscape", "vintage"],
    ingestedAt: ISO,
    signupRequired: false,
  },

  // =========================================================================
  // font-specimen (Wikimedia Commons specimens)
  // =========================================================================
  {
    id: "wm-helvetica-specimen",
    name: "Helvetica — Specimen Sheet",
    category: "font-specimen",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:HelveticaSpecimenCH.svg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/HelveticaSpecimenCH.svg/960px-HelveticaSpecimenCH.svg.png",
    license: "Public Domain",
    tags: ["typography", "helvetica", "swiss"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-helvetica-vs-neue",
    name: "Helvetica vs Helvetica Neue",
    category: "font-specimen",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Helvetica_vs_Helvetica_Neue.png",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Helvetica_vs_Helvetica_Neue.png/960px-Helvetica_vs_Helvetica_Neue.png",
    license: "Public Domain",
    tags: ["typography", "helvetica", "comparison"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-garamond-specimen",
    name: "Garamond — Specimen A",
    category: "font-specimen",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:GaramondSpecimenA.svg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/GaramondSpecimenA.svg/960px-GaramondSpecimenA.svg.png",
    license: "Public Domain",
    tags: ["typography", "garamond", "serif"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-adobe-garamond-glyphs",
    name: "Adobe Garamond Pro — Glyph Samples",
    category: "font-specimen",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Adobe_Garamond_Pro_glyph_samples.svg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Adobe_Garamond_Pro_glyph_samples.svg/960px-Adobe_Garamond_Pro_glyph_samples.svg.png",
    license: "Public Domain",
    tags: ["typography", "garamond", "glyphs"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-bodoni-sample",
    name: "Bodoni — Sample",
    category: "font-specimen",
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bodoni_sample.svg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Bodoni_sample.svg/960px-Bodoni_sample.svg.png",
    license: "Public Domain",
    tags: ["typography", "bodoni", "didone"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-bodoni-typeface-sample",
    name: "Bodoni — Typeface Sample",
    category: "font-specimen",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Bodoni_typeface_sample.png",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/8/88/Bodoni_typeface_sample.png",
    license: "Public Domain",
    tags: ["typography", "bodoni"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-futura-specimen",
    name: "Futura — Specimen",
    category: "font-specimen",
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Futura_Specimen.svg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Futura_Specimen.svg/960px-Futura_Specimen.svg.png",
    license: "Public Domain",
    tags: ["typography", "futura", "geometric"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-futura-typeface-specimen",
    name: "Futura — Typeface Specimen",
    category: "font-specimen",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Typeface_specimen_Futura.svg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Typeface_specimen_Futura.svg/960px-Typeface_specimen_Futura.svg.png",
    license: "Public Domain",
    tags: ["typography", "futura"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-times-new-roman-sample",
    name: "Times New Roman — Sample",
    category: "font-specimen",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Times_New_Roman_sample.svg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Times_New_Roman_sample.svg/960px-Times_New_Roman_sample.svg.png",
    license: "Public Domain",
    tags: ["typography", "times", "serif"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-caslon-1763-pica",
    name: "Caslon — Pica Black 1763",
    category: "font-specimen",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Caslon-specimen-1763-double-pica-black.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Caslon-specimen-1763-double-pica-black.jpg/960px-Caslon-specimen-1763-double-pica-black.jpg",
    license: "Public Domain",
    tags: ["typography", "caslon", "historical"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-caslon-specimen-historic",
    name: "A Specimen by William Caslon",
    category: "font-specimen",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:A_Specimen_by_William_Caslon.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/A_Specimen_by_William_Caslon.jpg/960px-A_Specimen_by_William_Caslon.jpg",
    license: "Public Domain",
    tags: ["typography", "caslon", "historical", "specimen"],
    ingestedAt: ISO,
    signupRequired: false,
  },

  // =========================================================================
  // public-domain-art (Wikimedia Commons masterpieces)
  // =========================================================================
  {
    id: "wm-mona-lisa",
    name: "Mona Lisa — Leonardo da Vinci",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mona_Lisa.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Mona_Lisa.jpg/960px-Mona_Lisa.jpg",
    license: "Public Domain",
    tags: ["renaissance", "portrait", "leonardo"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-starry-night",
    name: "The Starry Night — Vincent van Gogh",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Vincent_van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Vincent_van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/960px-Vincent_van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg",
    license: "Public Domain",
    tags: ["post-impressionism", "van-gogh", "night"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-the-scream",
    name: "The Scream — Edvard Munch",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Edvard_Munch,_1893,_The_Scream,_oil,_tempera_and_pastel_on_cardboard,_91_x_73_cm,_National_Gallery_of_Norway.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg/960px-Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg",
    license: "Public Domain",
    tags: ["expressionism", "munch", "modern"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-american-gothic",
    name: "American Gothic — Grant Wood",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Grant_Wood_-_American_Gothic_-_Google_Art_Project.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Grant_Wood_-_American_Gothic_-_Google_Art_Project.jpg/960px-Grant_Wood_-_American_Gothic_-_Google_Art_Project.jpg",
    license: "Public Domain",
    tags: ["regionalism", "wood", "american"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-las-meninas",
    name: "Las Meninas — Diego Velázquez",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Las_Meninas,_by_Diego_Vel%C3%A1zquez,_from_Prado_in_Google_Earth.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Las_Meninas%2C_by_Diego_Vel%C3%A1zquez%2C_from_Prado_in_Google_Earth.jpg/960px-Las_Meninas%2C_by_Diego_Vel%C3%A1zquez%2C_from_Prado_in_Google_Earth.jpg",
    license: "Public Domain",
    tags: ["baroque", "velazquez", "spanish"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-birth-of-venus",
    name: "Birth of Venus — Botticelli",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg/960px-Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg",
    license: "Public Domain",
    tags: ["renaissance", "botticelli", "mythology"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-primavera",
    name: "Primavera — Botticelli",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Botticelli-primavera.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Botticelli-primavera.jpg/960px-Botticelli-primavera.jpg",
    license: "Public Domain",
    tags: ["renaissance", "botticelli", "spring"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-great-wave-kanagawa",
    name: "The Great Wave off Kanagawa — Hokusai",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:The_Great_Wave_off_Kanagawa.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/The_Great_Wave_off_Kanagawa.jpg/960px-The_Great_Wave_off_Kanagawa.jpg",
    license: "Public Domain",
    tags: ["ukiyo-e", "hokusai", "japanese"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-great-wave-unrestored",
    name: "Great Wave (Unrestored) — Hokusai",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Great_Wave_unrestored.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Great_Wave_unrestored.jpg/960px-Great_Wave_unrestored.jpg",
    license: "Public Domain",
    tags: ["ukiyo-e", "hokusai", "japanese"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-tower-of-babel",
    name: "The Tower of Babel — Bruegel",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Pieter_Bruegel_the_Elder_-_The_Tower_of_Babel_(Vienna)_-_Google_Art_Project_-_edited.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Pieter_Bruegel_the_Elder_-_The_Tower_of_Babel_%28Vienna%29_-_Google_Art_Project_-_edited.jpg/960px-Pieter_Bruegel_the_Elder_-_The_Tower_of_Babel_%28Vienna%29_-_Google_Art_Project_-_edited.jpg",
    license: "Public Domain",
    tags: ["renaissance", "bruegel", "biblical"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-wanderer-fog",
    name: "Wanderer above the Sea of Fog — Friedrich",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg/960px-Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg",
    license: "Public Domain",
    tags: ["romanticism", "friedrich", "german"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-liberty-leading",
    name: "Liberty Leading the People — Delacroix",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Eug%C3%A8ne_Delacroix_-_Le_28_Juillet._La_Libert%C3%A9_guidant_le_peuple.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Eug%C3%A8ne_Delacroix_-_Le_28_Juillet._La_Libert%C3%A9_guidant_le_peuple.jpg/960px-Eug%C3%A8ne_Delacroix_-_Le_28_Juillet._La_Libert%C3%A9_guidant_le_peuple.jpg",
    license: "Public Domain",
    tags: ["romanticism", "delacroix", "french"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-creation-of-adam",
    name: "Creation of Adam — Michelangelo",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Michelangelo_-_Creation_of_Adam_(cropped).jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Michelangelo_-_Creation_of_Adam_%28cropped%29.jpg/960px-Michelangelo_-_Creation_of_Adam_%28cropped%29.jpg",
    license: "Public Domain",
    tags: ["renaissance", "michelangelo", "sistine"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-moulin-de-la-galette",
    name: "Bal du Moulin de la Galette — Renoir",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Pierre-Auguste_Renoir,_Le_Moulin_de_la_Galette.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Pierre-Auguste_Renoir%2C_Le_Moulin_de_la_Galette.jpg/960px-Pierre-Auguste_Renoir%2C_Le_Moulin_de_la_Galette.jpg",
    license: "Public Domain",
    tags: ["impressionism", "renoir", "paris"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-view-of-delft",
    name: "View of Delft — Vermeer",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Vermeer-view-of-delft.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Vermeer-view-of-delft.jpg/960px-Vermeer-view-of-delft.jpg",
    license: "Public Domain",
    tags: ["dutch-golden-age", "vermeer", "delft"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-whistlers-mother",
    name: "Whistler's Mother — James McNeill Whistler",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Whistlers_Mother_high_res.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Whistlers_Mother_high_res.jpg/960px-Whistlers_Mother_high_res.jpg",
    license: "Public Domain",
    tags: ["realism", "whistler", "portrait"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-dejeuner-sur-lherbe",
    name: "Le Déjeuner sur l'herbe — Manet",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:%C3%89douard_Manet_-_Le_D%C3%A9jeuner_sur_l%27herbe.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/%C3%89douard_Manet_-_Le_D%C3%A9jeuner_sur_l%27herbe.jpg/960px-%C3%89douard_Manet_-_Le_D%C3%A9jeuner_sur_l%27herbe.jpg",
    license: "Public Domain",
    tags: ["realism", "manet", "french"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-the-kiss-klimt",
    name: "The Kiss — Gustav Klimt",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Klimt_-_The_Kiss.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Klimt_-_The_Kiss.jpg/960px-Klimt_-_The_Kiss.jpg",
    license: "Public Domain",
    tags: ["symbolism", "klimt", "vienna"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-the-kiss-klimt-alt",
    name: "The Kiss (alt) — Klimt",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:The_Kiss_by_Gustav_Klimt.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/The_Kiss_by_Gustav_Klimt.jpg/960px-The_Kiss_by_Gustav_Klimt.jpg",
    license: "Public Domain",
    tags: ["symbolism", "klimt"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-nighthawks",
    name: "Nighthawks — Edward Hopper",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Nighthawks_by_Edward_Hopper_1942.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Nighthawks_by_Edward_Hopper_1942.jpg/960px-Nighthawks_by_Edward_Hopper_1942.jpg",
    license: "Public Domain",
    tags: ["realism", "hopper", "american"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-nighthawks-png",
    name: "Nighthawks (PNG) — Hopper",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Nighthawks_by_Edward_Hopper.png",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Nighthawks_by_Edward_Hopper.png/960px-Nighthawks_by_Edward_Hopper.png",
    license: "Public Domain",
    tags: ["realism", "hopper"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-water-lilies-monet",
    name: "Water Lilies — Monet",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Claude_Monet_-_Seerosen.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Claude_Monet_-_Seerosen.jpg/960px-Claude_Monet_-_Seerosen.jpg",
    license: "Public Domain",
    tags: ["impressionism", "monet", "lilies"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-water-lily-pond-detail",
    name: "Detail of Water-Lily Pond — Monet",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Detail_of_%22The_Water-Lily_Pond%22_by_Claude_Monet_02.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Detail_of_%22The_Water-Lily_Pond%22_by_Claude_Monet_02.jpg/960px-Detail_of_%22The_Water-Lily_Pond%22_by_Claude_Monet_02.jpg",
    license: "Public Domain",
    tags: ["impressionism", "monet"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-saturn-devouring",
    name: "Saturn Devouring His Son — Goya",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Francisco_de_Goya,_Saturno_devorando_a_su_hijo_(1819-1823).jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Francisco_de_Goya%2C_Saturno_devorando_a_su_hijo_%281819-1823%29.jpg/960px-Francisco_de_Goya%2C_Saturno_devorando_a_su_hijo_%281819-1823%29.jpg",
    license: "Public Domain",
    tags: ["romanticism", "goya", "dark"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-girl-with-pearl",
    name: "Girl with a Pearl Earring — Vermeer",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:1665_Girl_with_a_Pearl_Earring.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/1665_Girl_with_a_Pearl_Earring.jpg/960px-1665_Girl_with_a_Pearl_Earring.jpg",
    license: "Public Domain",
    tags: ["dutch-golden-age", "vermeer", "portrait"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-meisje-met-de-parel",
    name: "Meisje met de parel — Vermeer",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Meisje_met_de_parel.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Meisje_met_de_parel.jpg/960px-Meisje_met_de_parel.jpg",
    license: "Public Domain",
    tags: ["dutch-golden-age", "vermeer", "portrait"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-the-milkmaid-vermeer",
    name: "The Milkmaid — Vermeer",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Vermeer_-_The_Milkmaid.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/a/a8/Vermeer_-_The_Milkmaid.jpg",
    license: "Public Domain",
    tags: ["dutch-golden-age", "vermeer"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-sistine-adam",
    name: "Adam's Creation Sistine Chapel — Michelangelo",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:%27Adam%27s_Creation_Sistine_Chapel_ceiling%27_by_Michelangelo_JBU33cut.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/%27Adam%27s_Creation_Sistine_Chapel_ceiling%27_by_Michelangelo_JBU33cut.jpg/960px-%27Adam%27s_Creation_Sistine_Chapel_ceiling%27_by_Michelangelo_JBU33cut.jpg",
    license: "Public Domain",
    tags: ["renaissance", "michelangelo", "sistine"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-last-supper",
    name: "The Last Supper — Leonardo da Vinci",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Leonardo_da_Vinci_(1452-1519)_-_The_Last_Supper_(1495-1498).jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Leonardo_da_Vinci_%281452-1519%29_-_The_Last_Supper_%281495-1498%29.jpg/960px-Leonardo_da_Vinci_%281452-1519%29_-_The_Last_Supper_%281495-1498%29.jpg",
    license: "Public Domain",
    tags: ["renaissance", "leonardo", "biblical"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-school-of-athens",
    name: "The School of Athens — Raphael",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg/960px-%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg",
    license: "Public Domain",
    tags: ["renaissance", "raphael", "philosophy"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-calling-saint-matthew",
    name: "The Calling of Saint Matthew — Caravaggio",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:The_Calling_of_Saint_Matthew-Caravaggo_(1599-1600).jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/The_Calling_of_Saint_Matthew-Caravaggo_%281599-1600%29.jpg/960px-The_Calling_of_Saint_Matthew-Caravaggo_%281599-1600%29.jpg",
    license: "Public Domain",
    tags: ["baroque", "caravaggio", "biblical"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-night-watch",
    name: "The Night Watch — Rembrandt",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:The_Nightwatch_by_Rembrandt_-_Rijksmuseum.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/The_Nightwatch_by_Rembrandt_-_Rijksmuseum.jpg/960px-The_Nightwatch_by_Rembrandt_-_Rijksmuseum.jpg",
    license: "Public Domain",
    tags: ["dutch-golden-age", "rembrandt"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-night-watch-hd",
    name: "The Night Watch HD — Rembrandt",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:The_Night_Watch_-_HD.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/The_Night_Watch_-_HD.jpg/960px-The_Night_Watch_-_HD.jpg",
    license: "Public Domain",
    tags: ["dutch-golden-age", "rembrandt"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-guernica",
    name: "Guernica — Picasso",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Pablo_Picasso%27s_Guernica.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Pablo_Picasso%27s_Guernica.jpg/960px-Pablo_Picasso%27s_Guernica.jpg",
    license: "Public Domain",
    tags: ["cubism", "picasso", "war"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-sunflowers-vincent",
    name: "Sunflowers — Van Gogh",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Vincent_van_Gogh_-_Sunflowers_-_VGM_F458.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Vincent_van_Gogh_-_Sunflowers_-_VGM_F458.jpg/960px-Vincent_van_Gogh_-_Sunflowers_-_VGM_F458.jpg",
    license: "Public Domain",
    tags: ["post-impressionism", "van-gogh"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-sunflowers-munich",
    name: "Sunflowers (Munich) — Van Gogh",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Sunflowers_-_Vincent_van_Gogh_(Munich_version).jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Sunflowers_-_Vincent_van_Gogh_%28Munich_version%29.jpg/960px-Sunflowers_-_Vincent_van_Gogh_%28Munich_version%29.jpg",
    license: "Public Domain",
    tags: ["post-impressionism", "van-gogh"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-vincent-vangogh-128",
    name: "Cafe Terrace at Night — Van Gogh",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Vincent_Willem_van_Gogh_128.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Vincent_Willem_van_Gogh_128.jpg/960px-Vincent_Willem_van_Gogh_128.jpg",
    license: "Public Domain",
    tags: ["post-impressionism", "van-gogh", "night"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-frida-kahlo-portrait",
    name: "Frida Kahlo — Portrait by Guillermo Kahlo",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Frida_Kahlo,_by_Guillermo_Kahlo.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Frida_Kahlo%2C_by_Guillermo_Kahlo.jpg/960px-Frida_Kahlo%2C_by_Guillermo_Kahlo.jpg",
    license: "Public Domain",
    tags: ["portrait", "kahlo", "mexican"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-rousseau-005",
    name: "Henri Rousseau 005",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Henri_Rousseau_005.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Henri_Rousseau_005.jpg/960px-Henri_Rousseau_005.jpg",
    license: "Public Domain",
    tags: ["post-impressionism", "rousseau"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-botticelli-046",
    name: "Sandro Botticelli 046",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sandro_Botticelli_046.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Sandro_Botticelli_046.jpg/960px-Sandro_Botticelli_046.jpg",
    license: "Public Domain",
    tags: ["renaissance", "botticelli"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "wm-columna-rota-frida",
    name: "La Columna Rota — Frida Kahlo",
    category: "public-domain-art",
    source: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:La_Columna_Rota,_Frida_Kahlo,_Museo_Dolores_Olmedo.jpg",
    thumbUrl:
      "https://upload.wikimedia.org/wikipedia/commons/8/81/La_Columna_Rota%2C_Frida_Kahlo%2C_Museo_Dolores_Olmedo.jpg",
    license: "Public Domain",
    tags: ["surrealism", "kahlo", "mexican"],
    ingestedAt: ISO,
    signupRequired: false,
  },

  // =========================================================================
  // ui-kit (Cruip + Cruip tutorial assets)
  // =========================================================================
  {
    id: "cruip-open-react-logo",
    name: "Open React Template — Logo",
    category: "ui-kit",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/open-react-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/open-react-template/master/public/images/logo.svg",
    license: "GPL-3.0",
    tags: ["logo", "kit", "saas"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-tailwind-logo-04",
    name: "Tailwind Landing — Logo 04",
    category: "ui-kit",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/tailwind-landing-page-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/tailwind-landing-page-template/main/public/images/logo-04.svg",
    license: "GPL-3.0",
    tags: ["logo", "kit"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-tailwind-logo-05",
    name: "Tailwind Landing — Logo 05",
    category: "ui-kit",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/tailwind-landing-page-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/tailwind-landing-page-template/main/public/images/logo-05.svg",
    license: "GPL-3.0",
    tags: ["logo", "kit"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-tailwind-avatar-01",
    name: "Tailwind Landing — Avatar 01",
    category: "ui-kit",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/tailwind-landing-page-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/tailwind-landing-page-template/main/public/images/avatar-01.jpg",
    license: "GPL-3.0",
    tags: ["avatar", "kit"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-tailwind-avatar-02",
    name: "Tailwind Landing — Avatar 02",
    category: "ui-kit",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/tailwind-landing-page-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/tailwind-landing-page-template/main/public/images/avatar-02.jpg",
    license: "GPL-3.0",
    tags: ["avatar", "kit"],
    ingestedAt: ISO,
    signupRequired: false,
  },
  {
    id: "cruip-tailwind-avatar-03",
    name: "Tailwind Landing — Avatar 03",
    category: "ui-kit",
    source: "Cruip / GitHub",
    sourceUrl: "https://github.com/cruip/tailwind-landing-page-template",
    thumbUrl:
      "https://raw.githubusercontent.com/cruip/tailwind-landing-page-template/main/public/images/avatar-03.jpg",
    license: "GPL-3.0",
    tags: ["avatar", "kit"],
    ingestedAt: ISO,
    signupRequired: false,
  },

  // video category intentionally empty — no auth-free hot-linkable
  // video sources met the verification bar at ingest time.
];

export function getAssetsByCategory(
  category: WarehouseCategory,
): WarehouseAsset[] {
  return WAREHOUSE_SEED.filter((asset) => asset.category === category);
}

export function getAssetById(id: string): WarehouseAsset | undefined {
  return WAREHOUSE_SEED.find((asset) => asset.id === id);
}
