[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --omit=dev --no-audit --no-fund"]

[phases.build]
cmds = ["echo no-build"]

[start]
cmd = "HOSTNAME=0.0.0.0 PORT=$PORT node src/index.js"
