[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "corepack enable",
  "pnpm install --no-frozen-lockfile --ignore-scripts"
]

[phases.build]
cmds = [
  "pnpm build",
  "cp -r .next/static .next/standalone/.next/static",
  "cp -r public .next/standalone/public"
]

[variables]
ELECTRON_SKIP_BINARY_DOWNLOAD = "1"
ELECTRON_BUILDER_SKIP_DOWNLOAD = "1"

[start]
cmd = "HOSTNAME=0.0.0.0 PORT=$PORT node .next/standalone/server.js"
